FUNCTION ZWM_STORE_IROD_VALIDATE.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IM_USER) TYPE  WWWOBJID OPTIONAL
*"     VALUE(IM_WERKS) TYPE  WERKS_D OPTIONAL
*"     VALUE(IM_LGNUM) TYPE  LGNUM DEFAULT 'SDC'
*"     VALUE(IM_LGPLA) TYPE  LGPLA
*"     VALUE(IM_IROD) TYPE  ZIROD1
*"     VALUE(IM_ERROR_IF_TAGGED) TYPE  XFLD DEFAULT 'X'
*"     VALUE(IM_ERROR_IF_NOT_TAGGED) TYPE  XFLD OPTIONAL
*"  EXPORTING
*"     VALUE(EX_RETURN) TYPE  BAPIRET2
*"----------------------------------------------------------------------
  DATA:
    LV_LGPLA TYPE LGPLA,
    LV_WERKS TYPE WERKS_D,
    LV_USER  TYPE WWWOBJID.

  LV_USER = TO_UPPER( |{ IM_USER ALPHA = IN }| ).
  LV_WERKS = IM_WERKS.

  IF IM_USER IS INITIAL AND IM_WERKS IS INITIAL.
    EX_RETURN-MESSAGE = 'User Id Cannot Be Blank.'.
    EX_RETURN-TYPE = 'E'.
    RETURN.
  ENDIF.

  IF IM_WERKS IS INITIAL.
    SELECT
    SINGLE WERKS
      FROM ZWM_USR02
     WHERE UPPER( BNAME ) EQ @IM_USER
      INTO @LV_WERKS.
    IF SY-SUBRC IS NOT INITIAL.
      EX_RETURN-MESSAGE = 'User Id Cannot Be Blank.'.
      EX_RETURN-TYPE = 'E'.
      RETURN.
    ENDIF.
  ENDIF.

  SELECT
  SINGLE *
    FROM LAGP
   WHERE LGNUM = @IM_LGNUM
     AND LGTYP = @LV_WERKS+1(3)
     AND LGPLA = @IM_LGPLA
    INTO @DATA(LS_LAGP).

  IF SY-SUBRC NE 0 .
    EX_RETURN-TYPE = 'E'.
    MESSAGE E007(L1) WITH IM_LGPLA INTO EX_RETURN-MESSAGE.
    RETURN.
  ENDIF.

  SELECT *
    FROM ZWM_ST01_IROD_MC
   WHERE WERKS EQ @LV_WERKS
     AND IROD  EQ @IM_IROD
    INTO @DATA(LS_IROD)
      UP TO 1 ROWS.
  ENDSELECT.

  IF SY-SUBRC IS NOT INITIAL.
    EX_RETURN-TYPE = 'E'.
    MESSAGE E001(00) WITH |Invalid IROD { IM_IROD } | INTO EX_RETURN-MESSAGE.
    RETURN.
  ENDIF.


  SELECT *
    FROM ZWM_ST01_BIN_TAG
   WHERE WERKS EQ @LV_WERKS
     AND LGNUM EQ @IM_LGNUM
     AND IROD  EQ @IM_IROD
    INTO @DATA(LS_TAG)
      UP TO 1 ROWS.
  ENDSELECT.

  IF IM_ERROR_IF_TAGGED EQ ABAP_TRUE.
    IF LS_TAG-LGPLA IS NOT INITIAL.
      EX_RETURN-TYPE = 'E'.
      MESSAGE E001(00) WITH |Irod already tagged in bin { LS_TAG-LGPLA }| INTO EX_RETURN-MESSAGE.
*  ELSE.
*    EX_RETURN-TYPE = 'S'.
*    EX_RETURN-MESSAGE = 'Validated Successfully'.
    ENDIF.
  ELSEIF IM_ERROR_IF_NOT_TAGGED EQ ABAP_TRUE.
    IF LS_TAG-LGPLA IS INITIAL.
      EX_RETURN-TYPE = 'E'.
      MESSAGE E001(00) WITH |Irod { IM_IROD } not yet tagged| INTO EX_RETURN-MESSAGE.
    ENDIF.
  ENDIF.


*  EX_DATA = VALUE #( WERKS = LV_WERKS
*                     LGNUM = IM_LGNUM
*                     LGTYP = LV_WERKS+3(*)
*                     IROD  = LS_IROD-IROD
*                     LGPLA = IM_LGPLA ).
ENDFUNCTION.