FUNCTION ZSDC_ART_STA_RFC.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(EX_DATA) TYPE  ZSDC_ART_STATUS_TT OPTIONAL
*"  EXPORTING
*"     VALUE(EX_RETURN) TYPE  BAPIRET2
*"----------------------------------------------------------------------

*** VALIATION on Article and Store
  DATA : IT_DATA1 TYPE TABLE OF ZSDC_ART_STATUS_ST .
  DATA : IT_DATA2 TYPE TABLE OF ZSDC_ART_STATUS .
  DATA : LT_RETURN TYPE TABLE OF BAPIRET2 .

**  SELECT DISTINCT
**        W~WERKS ,
**     MARC~MATNR
**   FROM @IT_DATA AS D
***   INNER JOIN MARA AS M
***   ON M~MATNR = D~ARTICLE_NO
**   INNER JOIN MARC AS MARC
**   ON MARC~MATNR = D~ARTICLE_NO
**   AND MARC~WERKS = D~STORE_CODE
**   INNER JOIN T001W AS W
**   ON W~WERKS = D~STORE_CODE
**   AND W~VLFKZ = 'A'
**   INTO TABLE @IT_DATA1.
**
**  LOOP AT IT_DATA ASSIGNING FIELD-SYMBOL(<FS_VALIDATE>).
**    READ TABLE IT_DATA1 TRANSPORTING NO FIELDS
**                        WITH KEY STORE_CODE = <FS_VALIDATE>-STORE_CODE
**                                 ARTICLE_NO = <FS_VALIDATE>-ARTICLE_NO .
**    IF SY-SUBRC NE 0 .
**      EX_RETURN = VALUE #( TYPE    = 'E' MESSAGE = |Invalid Store against Material: { <FS_VALIDATE>-STORE_CODE }:{ <FS_VALIDATE>-ARTICLE_NO }| ).
**      RETURN.
**    ENDIF .
**
**  ENDLOOP .

  DATA(IT_DATA) = EX_DATA[] .

  SORT IT_DATA BY ARTICLE_NO STORE_CODE .
  DELETE ADJACENT DUPLICATES FROM IT_DATA COMPARING ARTICLE_NO STORE_CODE .

  LOOP AT IT_DATA ASSIGNING FIELD-SYMBOL(<FS_VALIDATE>).
**    Check if Article No. and Store Code already exists in ZSDC_ART_STATUS table
    SELECT SINGLE  ARTICLE_NO , STORE_CODE
       FROM ZSDC_ART_STATUS INTO @DATA(LS_ART_STATUS)
      WHERE ARTICLE_NO = @<FS_VALIDATE>-ARTICLE_NO
        AND STORE_CODE = @<FS_VALIDATE>-STORE_CODE .
    IF SY-SUBRC IS INITIAL .
      EX_RETURN = VALUE #( TYPE = 'E'  MESSAGE = |{ TEXT-002 }-{ <FS_VALIDATE>-ARTICLE_NO  }-{ TEXT-003 } { <FS_VALIDATE>-STORE_CODE }-{ TEXT-004 }| ).
      RETURN .
    ENDIF .

**Validate Material from MARA Table
    SELECT SINGLE MATNR FROM MARA INTO @DATA(LV_MATNR)
      WHERE MATNR = @<FS_VALIDATE>-ARTICLE_NO .
    IF SY-SUBRC NE 0 .
      EX_RETURN = VALUE #( TYPE    = 'E' MESSAGE = |{ TEXT-005 }-{ <FS_VALIDATE>-ARTICLE_NO }| ).
      RETURN.
    ENDIF .

** Validate Plant from T001W Table
    SELECT SINGLE WERKS FROM T001W INTO @DATA(LV_PLANT)
      WHERE WERKS = @<FS_VALIDATE>-STORE_CODE
       AND VLFKZ  = 'A'.

    IF SY-SUBRC NE 0 .
      EX_RETURN = VALUE #( TYPE = 'E' MESSAGE = | { TEXT-006 }-{ <FS_VALIDATE>-STORE_CODE } | ).
      RETURN .
    ENDIF .
  ENDLOOP .

  IT_DATA2 = VALUE #( FOR LS_DATA IN IT_DATA
                    ( STORE_CODE = LS_DATA-STORE_CODE
                      ARTICLE_NO = LS_DATA-ARTICLE_NO
                      ART_TYPE   = LS_DATA-ART_TYPE
                      CREATED_DATE = SY-DATUM
                      CREATED_TIME = SY-UZEIT
                      CREATED_BY   = SY-UNAME ) ) .

** Internal Data Save in ZSDC_ART_STATUS Table
  MODIFY ZSDC_ART_STATUS FROM TABLE IT_DATA2.
  COMMIT WORK.
  MESSAGE TEXT-007 TYPE 'S' .



ENDFUNCTION.