FUNCTION ZWM_CREATE_HU_AND_ASSIGN_TVS.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IM_LGNUM) TYPE  LGNUM DEFAULT 'V2R'
*"     VALUE(IM_VBELN) TYPE  VBELN_VL OPTIONAL
*"     VALUE(IM_USER) TYPE  WWWOBJID OPTIONAL
*"     VALUE(IM_EXIDV) TYPE  EXIDV OPTIONAL
*"  EXPORTING
*"     VALUE(EX_RETURN) TYPE  BAPIRET2
*"     VALUE(EX_HUDATA) TYPE  ZWM_HUDATA
*"  TABLES
*"      IT_DATA STRUCTURE  VERPO OPTIONAL
*"      IT_BIN_EMPTY STRUCTURE  ZWM_PLESS_BIN OPTIONAL
*"----------------------------------------------------------------------
  CLEAR: EX_RETURN.

  DATA: L_EXIDV            TYPE EXIDV,
        LV_EXIDV           TYPE EXIDV,
        LV_WERKS           TYPE WERKS_D,
        L_USER             TYPE WWWOBJID,
        LS_ZWM_HU_LOG      TYPE ZWM_HU_LOG,
        L_TOT_QTY          TYPE TMENG,
        L_TOT_QTY_S        TYPE STRING,
        LT_DATA            TYPE TAB_VERPO,
        LS_HEADER_PROPOSAL TYPE HUHDR_PROPOSAL,
        LS_HEADER          TYPE VEKPVB,
        LV_POSNR           TYPE POSNR,
        LS_HU_BIN          TYPE ZWM_HU_BIN,
        LS_VERPO           LIKE LINE OF IT_DATA,
        LS_HHT_DATA        TYPE VERPO,
        LS_PICKLIST        TYPE ZADVERB_PICKLIST,
        LS_HUHEADER        TYPE BAPIHUHEADER,
        LT_RETURN          TYPE BAPIRET2_T,
        LT_HU_BIN          TYPE STANDARD TABLE OF ZWM_HU_BIN,
        LR_DATA            TYPE REF TO VERPO,
        LR_RETURN          TYPE REF TO BAPIRET2,
        LV_EXIDV1          TYPE ZSAPHU.

  DATA: L_MATNR      TYPE MATNR,
        L_VBELN      TYPE VBELN_VL,
        L_TMENG      TYPE TMENG,
        LS_VBKOK_WA  TYPE VBKOK,
        LS_PROTT     TYPE PROTT,
        LF_ERROR_GI  TYPE XFELD,
        L_TIME_STAMP TYPE TIMESTAMPL,
        L_BKG_ERROR  TYPE CHAR1,
        LS_TID       TYPE ARFCTID,
        LT_ERRORS    TYPE TABLE OF ARFCERRORS,
        LT_PROT      TYPE TABLE OF PROTT,
        LS_TMP       TYPE VERPO.

*Paperless Picking X mark BINS
  DATA: GT_BIN_EMPTY     TYPE TABLE OF ZWM_PLESS_BIN,
        GT_BIN_EMPTY_SUM TYPE TABLE OF ZWM_PLESS_BIN,
        GW_BIN_EMPTY_SUM TYPE ZWM_PLESS_BIN,
        GW_BIN_EMPTY     TYPE ZWM_PLESS_BIN,
        WA_BIN_EMPTY     TYPE ZWM_PLESS_BIN,
        GT_DATA          TYPE TABLE OF VERPO,
        IT_PICKLIST      TYPE ZADVERB_PICKLIST_TT,
        GT_DATA_SUM      TYPE TABLE OF VERPO,
        GW_DATA          TYPE VERPO,
        GW_DATA_SUM      TYPE VERPO.

  DATA : LS_HULOG TYPE ZWM_HU_STAT_LOG .
*Update HU Backup data - VKS-22.01.2021
  DATA: LS_DATA         TYPE ZBACKUPHU_DATA,
        LT_HU_PRINT_TVS TYPE STANDARD TABLE OF ZWM_HUDATA,
        LT_VEPO1        TYPE TABLE OF VEPO,
        LS_VEPO1        TYPE VEPO,
        LS_VEKP1        TYPE VEKP,
*        LS_HU_BIN TYPE ZWM_HU_BIN,
        LV_HUQTY        TYPE VEMNG,
        LS_EXREF        TYPE ZWM_EXREF.
*  GT_BIN_EMPTY = IT_BIN_EMPTY[].

  DATA: GV_GRS_WT TYPE BRGEW.  " ++BHARAT ON 04.08.2022

*Convert into internal format

  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT  = IM_VBELN
    IMPORTING
      OUTPUT = L_VBELN.

  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT  = IM_USER
    IMPORTING
      OUTPUT = L_USER.

  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT  = IM_EXIDV
    IMPORTING
      OUTPUT = LV_EXIDV.

  SELECT SINGLE SAP_HU FROM ZWM_EXREF
                      WHERE EXIDV EQ @LV_EXIDV
                      AND PROCESS EQ 'X'
                      INTO @DATA(LV_PROCESS).
  IF SY-SUBRC IS INITIAL AND LV_PROCESS IS NOT INITIAL.
    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
      EXPORTING
        INPUT  = LV_PROCESS
      IMPORTING
        OUTPUT = LV_PROCESS.
    CONCATENATE 'Hu'(013) LV_PROCESS 'Created Successfully'(011) '& submitted in background'(019) INTO EX_RETURN-MESSAGE SEPARATED BY SPACE.
    RETURN.
  ENDIF.

  UPDATE ZWM_EXREF SET PROCESS = 'X'
                   WHERE EXIDV EQ LV_EXIDV.
  COMMIT WORK AND WAIT.

  GT_DATA = IT_DATA[].

  SORT IT_BIN_EMPTY[] BY VBELN VLPLA.
*  DELETE ADJACENT DUPLICATES FROM IT_BIN_EMPTY[] COMPARING VBELN VLPLA.
  DELETE IT_BIN_EMPTY[] WHERE BIN_EMPTY_I EQ ''.
  IF  IT_BIN_EMPTY[] IS NOT INITIAL.
    MODIFY ZWM_PLESS_BIN FROM TABLE IT_BIN_EMPTY[].
  ENDIF.
*End code



  IF IT_DATA[] IS INITIAL .
    EX_RETURN-TYPE = 'E'.
    EX_RETURN-MESSAGE = 'No Data Scan'.
    RETURN.
  ENDIF.

*Checking Zero Qnty
  READ TABLE IT_DATA INTO LS_TMP WITH KEY TMENG = 0.
  IF SY-SUBRC = 0.
    EX_RETURN-TYPE = C_ERROR.
    EX_RETURN-MESSAGE = 'Zero Qnty found in Scan Data'.
    RETURN.
  ENDIF.

  LT_DATA[] = IT_DATA[].

*Delete duplicate material
*  LT_DATA = IT_DATA[].
  SORT LT_DATA BY P_MATERIAL.
  DELETE ADJACENT DUPLICATES FROM LT_DATA COMPARING P_MATERIAL.

*Generate Handling Unit
  IF LINES( LT_DATA ) GT 1.
    EX_RETURN-TYPE = C_ERROR.
    EX_RETURN-MESSAGE = 'Use only one packaging material at a time'.
    RETURN.
  ENDIF.

  PERFORM F_VALIDATE_FOR_QUANTITY USING L_VBELN L_EXIDV IT_DATA[] CHANGING EX_RETURN.
  IF EX_RETURN IS NOT INITIAL.
    RETURN.
  ENDIF.

* Create a HU without ITEMS
  CALL FUNCTION 'ZWM_UPDATE_PACKAGING' DESTINATION 'NONE'
    EXPORTING
      IM_LGNUM            = IM_LGNUM
      IM_VBELN            = L_VBELN
      IM_EXIDV            = '$1'
    IMPORTING
      EX_EXIDV            = L_EXIDV
    TABLES
      IT_DATA             = LT_DATA
    EXCEPTIONS
      UPDATE_NOT_POSSIBLE = 1
      OTHERS              = 2.

  IF SY-SUBRC <> 0.
    EX_RETURN-TYPE = C_ERROR.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 INTO EX_RETURN-MESSAGE.
    RETURN.
  ENDIF.

  LT_DATA[] = IT_DATA[].
  GET TIME STAMP FIELD L_TIME_STAMP.
  CALL FUNCTION 'ZWM_UPDATE_PACKAGING_BG'
    IN BACKGROUND TASK AS SEPARATE UNIT
    EXPORTING
      IM_LGNUM      = IM_LGNUM
      IM_VBELN      = L_VBELN
      IM_EXIDV      = L_EXIDV
      IM_USER       = L_USER
      IM_TIME_STAMP = L_TIME_STAMP
    TABLES
      IT_DATA       = LT_DATA.

*Could the background task initialized?
  CALL FUNCTION 'ID_OF_BACKGROUNDTASK'
    IMPORTING
      TID = LS_TID.

  IF LS_TID EQ SPACE.
    L_BKG_ERROR = 'X'.
    CALL FUNCTION 'BAPI_HU_DELETE'
      EXPORTING
        HUKEY  = L_EXIDV
      TABLES
        RETURN = LT_RETURN.

    EX_RETURN-TYPE = C_ERROR.
    EX_RETURN-MESSAGE = 'Error executing in background'(018).
    RETURN.
  ELSE.
    CALL FUNCTION 'STATUS_OF_BACKGROUNDTASK'
      EXPORTING
        TID           = LS_TID
      TABLES
        ERRORTAB      = LT_ERRORS
      EXCEPTIONS
        COMMUNICATION = 1
        RECORDED      = 2
        ROLLBACK      = 3
        OTHERS        = 4.

    IF  SY-SUBRC NE 0 AND SY-SUBRC NE 2.
      L_BKG_ERROR = 'X'.
      CALL FUNCTION 'BAPI_HU_DELETE'
        EXPORTING
          HUKEY  = L_EXIDV
        TABLES
          RETURN = LT_RETURN.
      EX_RETURN-TYPE = C_ERROR.
      EX_RETURN-MESSAGE = 'Error executing in background'(018).
      RETURN.
    ENDIF.
  ENDIF.

  COMMIT WORK AND WAIT.
  SELECT SINGLE * FROM ZSTODO_DATA INTO @DATA(LS_STODO) WHERE VBELN = @IM_VBELN.
  SELECT SINGLE * FROM EKKO INTO @DATA(LS_EKKO)  WHERE EBELN = @LS_STODO-EBELN.
  SELECT SINGLE * FROM T001W INTO @DATA(LS_T001W) WHERE WERKS EQ @LS_EKKO-SUBMI+0(4).
  IF LS_STODO-ZPLANT IS INITIAL .
    LS_STODO-ZPLANT = LS_STODO-WERKS.
  ENDIF.
  IF L_BKG_ERROR = ''.
    DATA: LS_TMP1 TYPE VEKP,
          LS_TMP2 TYPE VEPO.

*Check data updated against New HU - VKS-26.02.2021
    DO 10 TIMES.

      WAIT UP TO '3' SECONDS.

      SELECT SINGLE * FROM VEKP INTO LS_TMP1 WHERE EXIDV = L_EXIDV.
      IF SY-SUBRC = 0.
        SELECT SINGLE * FROM VEPO INTO LS_TMP2 WHERE VENUM = LS_TMP1-VENUM.
        IF SY-SUBRC = 0.
          EXIT.
        ENDIF.
      ENDIF.
      CLEAR: LS_TMP1, LS_TMP2.
    ENDDO.

*Check Blank,Zero Qty & Differ Qty Created HU - VKS-22.01.2021
    DATA: LS_VEKP TYPE VEKP,
          LS_VEPO TYPE VEPO,
          LT_VEPO TYPE TABLE OF VEPO,
          LV_FLAG TYPE C VALUE '',
          LS_TEMP TYPE VERPO,
          LV_QTY  TYPE TMENG.

    SELECT SINGLE * FROM VEKP INTO LS_VEKP WHERE EXIDV = L_EXIDV.
    IF SY-SUBRC = 0.
      SELECT SINGLE * FROM VEPO INTO LS_VEPO WHERE VENUM = LS_VEKP-VENUM.
      IF LS_VEPO IS INITIAL.
        DELETE FROM VEKP WHERE EXIDV = L_EXIDV.
        DELETE FROM VEPO WHERE VENUM = LS_VEKP-VENUM.
        DELETE FROM ZWM_HU_BIN WHERE SAP_HU = L_EXIDV.  " ++bharat on 28.06.2022
        EX_RETURN-TYPE = C_ERROR.
        EX_RETURN-MESSAGE = 'ERROR: HU is blank can not be saved, Try again'.
        LV_FLAG = 'X'.
        RETURN.
      ENDIF.
      CLEAR: LS_VEPO.

      SELECT SINGLE * FROM VEPO INTO LS_VEPO WHERE VENUM = LS_VEKP-VENUM AND VEMNG = 0.
      IF SY-SUBRC = 0.
        DELETE FROM VEKP WHERE EXIDV = L_EXIDV.
        DELETE FROM VEPO WHERE VENUM = LS_VEKP-VENUM.
*        DELETE FROM zwm_hudata WHERE sap_hu = l_exidv. "--bharat on 28.06.0222
        DELETE FROM ZWM_HU_BIN WHERE SAP_HU = L_EXIDV.  "  ++bharat on 28.06.2022
        EX_RETURN-TYPE = C_ERROR.
        EX_RETURN-MESSAGE = 'ERROR: Zero Qty HU can not be saved, Try again'.
        LV_FLAG = 'X'.
        RETURN.
      ENDIF.
      CLEAR: LS_VEPO.

      SELECT * FROM VEPO INTO TABLE LT_VEPO WHERE VENUM = LS_VEKP-VENUM.
      SORT LT_VEPO BY VBELN MATNR.  SORT LT_DATA BY VBELN MATNR.
      LOOP AT LT_VEPO INTO LS_VEPO WHERE VBELN = L_VBELN. "Parallel cussor
        READ TABLE IT_DATA INTO LS_TEMP WITH KEY VBELN = L_VBELN MATNR = LS_VEPO-MATNR BINARY SEARCH.
        IF SY-SUBRC = 0.
          LOOP AT IT_DATA INTO LS_TEMP FROM SY-TABIX.
            IF LS_TEMP-MATNR <> LS_VEPO-MATNR.
              EXIT.
            ENDIF.
            LV_QTY = LV_QTY + LS_TEMP-TMENG.
          ENDLOOP.
          IF LS_VEPO-VEMNG <> LV_QTY.
            DELETE FROM VEKP WHERE EXIDV = L_EXIDV.
            DELETE FROM VEPO WHERE VENUM = LS_VEKP-VENUM.
*            DELETE FROM zwm_hudata WHERE sap_hu = l_exidv.  " --Bharat on 28.06.2022
            DELETE FROM ZWM_HU_BIN WHERE SAP_HU = L_EXIDV.  " ++Bharat on 28.06.2022
            EX_RETURN-TYPE = C_ERROR.
            EX_RETURN-MESSAGE = 'ERROR: Article Qty in Generated Int.HU & Scanning is not match, Try again'.
            LV_FLAG = 'X'.
            RETURN.
          ENDIF.
        ENDIF.
        CLEAR: LS_VEPO,LV_QTY.
      ENDLOOP.
      CLEAR: LS_VEKP.
    ENDIF.
*End code

    IF L_BKG_ERROR = '' AND LV_FLAG = ''.
      WRITE L_EXIDV TO G_EXIDV.

      CONCATENATE 'Hu'(013) G_EXIDV 'Created Successfully'(011) '& submitted in background'(019) INTO EX_RETURN-MESSAGE SEPARATED BY SPACE.
      EX_RETURN-MESSAGE_V1 = G_EXIDV.
      LS_ZWM_HU_LOG-EXIDV = L_EXIDV.
      LS_ZWM_HU_LOG-ERNAM = L_USER.
      INSERT ZWM_HU_LOG FROM LS_ZWM_HU_LOG.

** Start bharat on 04.08.2022  Calculate Handling Unit weight
      IF GT_DATA IS NOT INITIAL.
        DATA(GT_DATA2) = GT_DATA .
        SORT GT_DATA2 ASCENDING BY MATNR.
        SELECT A~MATNR, SUM( A~BRGEW ) AS BRGEW FROM MARA AS A
            INNER JOIN @GT_DATA2 AS B
            ON  A~MATNR = B~MATNR
             GROUP BY A~MATNR
            INTO TABLE @DATA(GT_BRGEW).
      ENDIF.

      IF LT_DATA IS NOT INITIAL.
        DATA(LT_DATA2) = LT_DATA .
        SORT LT_DATA2 BY P_MATERIAL.
        DELETE ADJACENT DUPLICATES FROM LT_DATA2 COMPARING P_MATERIAL.
        SELECT A~MATNR, SUM( A~BRGEW ) AS BRGEW FROM MARA AS A
            INNER JOIN @LT_DATA2 AS B
            ON  A~MATNR = B~P_MATERIAL
             GROUP BY A~MATNR
            INTO TABLE @DATA(GT_BRGEW2).
      ENDIF.

      APPEND LINES OF GT_BRGEW TO GT_BRGEW2.
      LOOP AT GT_BRGEW2 INTO DATA(GW_BRGEW).
        GV_GRS_WT = GV_GRS_WT + GW_BRGEW-BRGEW.
      ENDLOOP.

      IF GV_GRS_WT IS NOT INITIAL.
        GV_GRS_WT = GV_GRS_WT / 1000.   " Convert GM to KG
      ENDIF.

      UPDATE VEKP SET: NTGEW = GV_GRS_WT
                       SEALN4 =  LS_STODO-ZPLANT
                       GEWEI = 'KG'
                       GEWEI_MAX = 'KG'
             WHERE EXIDV = L_EXIDV.
      COMMIT WORK AND WAIT.


    ENDIF.
  ELSE.
    ROLLBACK WORK.
    EX_RETURN-TYPE = C_ERROR.
    EX_RETURN-MESSAGE = ' Executing in background'(018).
    RETURN.
  ENDIF.

  SELECT SINGLE * FROM ZWM_EXREF INTO LS_EXREF WHERE EXIDV = LV_EXIDV.
*Update HU in table
  IF L_EXIDV IS NOT INITIAL AND LV_FLAG = ''.
    CLEAR: LV_EXIDV1.

    SELECT SINGLE SAP_HU FROM ZWM_EXREF INTO LV_EXIDV1  WHERE SAP_HU = L_EXIDV.
    IF SY-SUBRC = 0.
      EX_RETURN-TYPE = C_ERROR.
      EX_RETURN-MESSAGE = ' Internal Hu Already Exist'(023).
      RETURN.
    ELSE.
      UPDATE ZWM_EXREF SET: SAP_HU = L_EXIDV
                            ADATUM = SY-DATUM
                            HHT_ID = L_USER
                      WHERE EXIDV = LV_EXIDV.
      COMMIT WORK AND WAIT.
    ENDIF.
  ENDIF.

*  SELECT SINGLE * FROM ZSTODO_DATA INTO @DATA(LS_STODO) WHERE VBELN = @IM_VBELN.

  SELECT SINGLE KUNNR FROM LIKP INTO @DATA(LV_SITE)
    WHERE VBELN = @L_VBELN.

  IF IM_USER NE 'PTL'.
    CLEAR LV_POSNR .
    LOOP AT IT_DATA INTO LS_HHT_DATA .
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
        EXPORTING
          INPUT  = LS_HHT_DATA-MATNR
        IMPORTING
          OUTPUT = LS_HHT_DATA-MATNR.

      LV_POSNR = LV_POSNR + 1.
      LS_HU_BIN-SAP_HU = L_EXIDV .
      LS_HU_BIN-POSNR = LV_POSNR  .
      LS_HU_BIN-EXIDV = LV_EXIDV .
      LS_HU_BIN-VBELN = L_VBELN .
      LS_HU_BIN-ABATCH = LS_STODO-ABATCH .
      LS_HU_BIN-HHT_USER = L_USER .
      LS_HU_BIN-WERKS = LV_SITE."LS_EXREF-DWERKS.
      LS_HU_BIN-MATNR = LS_HHT_DATA-MATNR.
      LS_HU_BIN-MENGE = LS_HHT_DATA-TMENG.
      LS_HU_BIN-LGPLA = LS_HHT_DATA-RFBEL.
      LS_HU_BIN-ERDAT = SY-DATUM.
      LS_HU_BIN-UZEIT = SY-UZEIT.

      LS_HU_BIN-STDATE = SY-DATUM ." LS_HHT_DATA-WDATU.
      LS_HU_BIN-STTIME = LS_HHT_DATA-RFPOS.

      APPEND LS_HU_BIN TO LT_HU_BIN .
      CLEAR LS_HU_BIN.

      LS_PICKLIST-SAP_HU = L_EXIDV .
      LS_PICKLIST-EXIDV = LV_EXIDV .
      LS_PICKLIST-ERNAM = L_USER .
      LS_PICKLIST-WERKS = LS_EXREF-DWERKS .
      LS_PICKLIST-CRATE =  '' .
      LS_PICKLIST-PROCESS =  'CLA' .
      LS_PICKLIST-DESTINATION =  'CLA' .
      LS_PICKLIST-MATNR =  LS_HHT_DATA-MATNR .
      LS_PICKLIST-PICKLISTNO =  L_VBELN .
      LS_PICKLIST-MENGE =  LS_HHT_DATA-TMENG.

      COLLECT LS_PICKLIST INTO IT_PICKLIST.
      CLEAR LS_PICKLIST.
      CLEAR LS_DATA .
    ENDLOOP.

    SELECT
      A~SAP_HU,
      A~VBELN,
      A~WERKS,
      A~HHT_USER,
      SUM( A~MENGE ) AS MENGE
      FROM @LT_HU_BIN AS A
      GROUP BY
       A~SAP_HU,
      A~VBELN,
      A~WERKS,
      A~HHT_USER
      INTO TABLE @DATA(LT_PRINT).
    IF SY-SUBRC IS INITIAL.

      EX_HUDATA-SAP_HU = VALUE #( LT_PRINT[ 1 ]-SAP_HU OPTIONAL  ).
      EX_HUDATA-SAP_HU = |{ EX_HUDATA-SAP_HU ALPHA = OUT } |.
      EX_HUDATA-VEMNG = VALUE #( LT_PRINT[ 1 ]-MENGE OPTIONAL  ).

      IF LS_STODO-ZPLANT IS NOT INITIAL .
        EX_HUDATA-HUB = VALUE #( LT_PRINT[ 1 ]-WERKS OPTIONAL  ). .
        SELECT SINGLE NAME1 FROM T001W INTO EX_HUDATA-HUB_NAME WHERE WERKS = EX_HUDATA-HUB.

        EX_HUDATA-DWERKS = LS_STODO-ZPLANT .
        EX_HUDATA-REF_DWERKS = LS_STODO-ZPLANT .


      ELSE.
        EX_HUDATA-DWERKS = VALUE #( LT_PRINT[ 1 ]-WERKS OPTIONAL  ).
      ENDIF.

      EX_HUDATA-HHT_ID = VALUE #( LT_PRINT[ 1 ]-HHT_USER OPTIONAL  ).
      EX_HUDATA-HHT_ID = |{ EX_HUDATA-HHT_ID ALPHA = OUT } |.
      EX_HUDATA-UNAME = SY-UNAME.
*      ex_hudata-hub = ls_ekko-submi.
*      ex_hudata-hub_name = ls_t001w-name1.
      CONCATENATE SY-DATUM+6(2)
                  SY-DATUM+4(2)
                  SY-DATUM+0(4)
                  INTO EX_HUDATA-DATUM SEPARATED BY '.'.


*      EX_HUDATA-DATUM = '09.09.2024'."SY-DATUM.
*      EX_HUDATA-ERZET = SY-UZEIT.
      EX_HUDATA-WEIGHT = 0.
      EX_HUDATA-GEWEI = 'KG'.
      EX_HUDATA-SWERKS = LS_STODO-LIFNR.
      EX_HUDATA-TVS_TEXT = LS_STODO-ABATCH ."|SALE|.
      EX_HUDATA-ABATCH = LS_STODO-ABATCH ."|SALE|.
      EX_HUDATA-VBELN = L_VBELN.


      SELECT SINGLE PRIORITY
        FROM ZWM_DEL_HHT_MAP
        INTO @EX_HUDATA-PRIORITY
        WHERE
        VBELN = @L_VBELN.


      SELECT SINGLE NAME1 FROM T001W
        WHERE WERKS = @EX_HUDATA-DWERKS
        INTO @EX_HUDATA-DWERKS_NAME1.


      SELECT SINGLE * FROM ZT001W_ALT INTO @DATA(LS_NAME) WHERE WERKS = @EX_HUDATA-DWERKS.
      IF SY-SUBRC IS INITIAL .
        EX_HUDATA-DWERKS_NAME1 = LS_NAME-NAME1.
      ENDIF.
      LS_HULOG-EXIDV =  VALUE #( LT_PRINT[ 1 ]-SAP_HU OPTIONAL ).
      LS_HULOG-PROC_STAT = 'PICKING'.
      LS_HULOG-STATUS = 'CREATE'.
      LS_HULOG-STORE = LS_STODO-ZPLANT.
      LS_HULOG-SWERKS = LS_STODO-LIFNR.
      LS_HULOG-WERKS = LS_STODO-WERKS.

      APPEND EX_HUDATA TO LT_HU_PRINT_TVS.

    ENDIF.



    CALL FUNCTION 'ZWM_RFC_STORE_HU_STATUS_SAVE'
      EXPORTING
        IM_USER = EX_HUDATA-HHT_ID
        IM_DATA = LS_HULOG
* IMPORTING
*       EX_RETURN       =
      .
*** call FM V05 to V61
*** sap hu EX_HUDATA-SAP_HU
************************ADDED BY ABHI 23/04/2025****************
    DATA : LS_RETURN TYPE BAPIRET2 .
*************************************    DATA : LV_TANUM TYPE TANUM.
*************************************    CALL FUNCTION 'ZWM_TO_CREATE_MVT_TYPE'
*************************************      EXPORTING
*************************************        IM_LGNUM           = 'V2R'
*************************************        IM_BWLVS           = '840'
*************************************        IM_EXIDV           = EX_HUDATA-SAP_HU
*************************************        IM_LGPLA           = EX_HUDATA-VBELN
*************************************      IMPORTING
*************************************        EX_RETURN          = LS_RETURN
*************************************        L_TANUM            = LV_TANUM
*************************************      EXCEPTIONS
*************************************        TO_CREATION_FAILED = 1.
*
*    IF LS_RETURN-TYPE = 'E'.
*      WRITE: / 'Error in stock transfer:', LS_RETURN-MESSAGE.
*    ELSE.
*      WRITE: / 'Transfer completed. Document Number:', LV_TANUM.
*    ENDIF.

***************************************************************
    DATA : EV_DOCNO TYPE ZZDOCNO.
*    DATA : LS_RETURN TYPE BAPIRET2 .
    LOOP AT LT_HU_PRINT_TVS ASSIGNING FIELD-SYMBOL(<LFS_TVS>).
      <LFS_TVS>-SAP_HU = |{ EX_HUDATA-SAP_HU ALPHA = IN }|.
      <LFS_TVS>-ERZET = SY-UZEIT.

      IF <LFS_TVS>-DWERKS IS INITIAL.
        SELECT SINGLE _EKKO~SUBMI FROM EKKO AS _EKKO
                                  INNER JOIN LIPS AS _LIPS
                                  ON _EKKO~EBELN EQ _LIPS~VGBEL
                                  WHERE _LIPS~VGBEL NE ''
                                  INTO @DATA(LV_STORE).
        IF LV_STORE IS NOT INITIAL.
          <LFS_TVS>-DWERKS = LV_STORE.
        ENDIF.
      ENDIF.

    ENDLOOP.

    MODIFY ZWM_HUDATA FROM TABLE LT_HU_PRINT_TVS.
    MODIFY ZWM_HU_BIN FROM TABLE  LT_HU_BIN  .
    CALL FUNCTION 'ZAPI_ADVERB_SAVE_CARTHU'
      IMPORTING
        EX_RETURN   = LS_RETURN
        EV_DOCNO    = EV_DOCNO
      TABLES
        IT_PICKLIST = IT_PICKLIST.
  ENDIF.

  SELECT SINGLE * FROM VEKP INTO LS_VEKP1 WHERE EXIDV = L_EXIDV.
  IF SY-SUBRC = 0 AND SY-TCODE = ''.
    LS_DATA-SWERKS = LS_VEKP1-WERKS.
    LS_DATA-VENUM  = LS_VEKP1-VENUM.
    LS_DATA-SAP_HU = LS_VEKP1-EXIDV.
    LS_DATA-VBELN  = L_VBELN.
    LS_DATA-DATUM  = SY-DATUM.
    LS_DATA-ERZET  = SY-UZEIT.
    LS_DATA-UNAME  = SY-UNAME.
    LS_DATA-TCODE  = 'HHT'.

*    IF SY-SUBRC = 0.
    LS_DATA-DWERKS = LS_EXREF-DWERKS.
    LS_DATA-EXIDV  = LS_EXREF-EXIDV.
*    ENDIF.

    SELECT * FROM VEPO INTO TABLE LT_VEPO1 WHERE VENUM = LS_VEKP1-VENUM.
    LOOP AT LT_VEPO1 INTO LS_VEPO1.
      LV_HUQTY = LV_HUQTY + LS_VEPO1-VEMNG.
    ENDLOOP.
    LS_DATA-PQNTY  = LV_HUQTY.

    DELETE FROM ZBACKUPHU_DATA WHERE EXIDV = LS_DATA-EXIDV.
    MODIFY ZBACKUPHU_DATA FROM LS_DATA.
    CLEAR: LS_DATA,LS_VEPO1,LS_VEKP1,LV_HUQTY.
    REFRESH: LT_VEPO1.
  ENDIF.

*Paperless Picking Remove Del.from Drop Down after Complete Scan
  IF L_BKG_ERROR = '' AND LV_FLAG = ''.
    DATA: LT_LIPS      TYPE TABLE OF LIPS,
          LT_VEKP2     TYPE TABLE OF VEKP,
          LT_VEPO2     TYPE TABLE OF VEPO,
          LT_BIN_EMPTY TYPE TABLE OF ZWM_PLESS_BIN,
          LS_BIN_EMPTY TYPE ZWM_PLESS_BIN,
          LS_VEKP2     TYPE VEKP,
          LS_VEPO2     TYPE VEPO,
          LS_LIPS      TYPE LIPS,
          LS_ITDATA    TYPE VERPO.

    SELECT * FROM LIPS INTO TABLE LT_LIPS WHERE VBELN = IM_VBELN AND POSNR < 900000.
    IF SY-SUBRC = 0.
      SELECT * FROM ZWM_PLESS_BIN INTO TABLE LT_BIN_EMPTY WHERE VBELN = IM_VBELN.
      IF SY-SUBRC = 0.
        LOOP AT LT_BIN_EMPTY INTO LS_BIN_EMPTY WHERE BIN_EMPTY_I = 'X'. "Check Mark delete
          DELETE LT_LIPS WHERE MATNR = LS_BIN_EMPTY-MATNR.
        ENDLOOP.
      ENDIF.

      LOOP AT IT_DATA INTO LS_ITDATA. "Current Scan mins
        CALL FUNCTION 'CONVERSION_EXIT_MATN1_INPUT'
          EXPORTING
            INPUT  = LS_ITDATA-MATNR
          IMPORTING
            OUTPUT = LS_ITDATA-MATNR.

        READ TABLE LT_LIPS INTO LS_LIPS WITH KEY MATNR = LS_ITDATA-MATNR.
        IF SY-SUBRC = 0.
          LS_LIPS-LFIMG = LS_LIPS-LFIMG - LS_ITDATA-TMENG.
          MODIFY LT_LIPS FROM LS_LIPS INDEX SY-TABIX.
        ENDIF.
      ENDLOOP.

      SELECT * FROM VEKP INTO TABLE LT_VEKP2 WHERE VBELN_GEN = IM_VBELN "Old Partial Del.mins
        AND EXIDV <> L_EXIDV .
      IF SY-SUBRC = 0.
        SELECT * FROM VEPO INTO TABLE LT_VEPO2 FOR ALL ENTRIES IN LT_VEKP2
          WHERE VENUM = LT_VEKP2-VENUM.
        IF SY-SUBRC = 0.
          LOOP AT LT_VEPO2 INTO LS_VEPO2.
            CALL FUNCTION 'CONVERSION_EXIT_MATN1_INPUT'
              EXPORTING
                INPUT  = LS_VEPO2-MATNR
              IMPORTING
                OUTPUT = LS_VEPO2-MATNR.

            READ TABLE LT_LIPS INTO LS_LIPS WITH KEY MATNR = LS_VEPO2-MATNR.
            IF SY-SUBRC = 0.
              LS_LIPS-LFIMG = LS_LIPS-LFIMG - LS_VEPO2-VEMNG.
              MODIFY LT_LIPS FROM LS_LIPS INDEX SY-TABIX.
            ENDIF.
          ENDLOOP.
        ENDIF.
      ENDIF.

      DELETE LT_LIPS WHERE LFIMG = 0.
      IF LT_LIPS IS INITIAL.
        UPDATE ZWM_DEL_HHT_MAP SET DLVFLAG = 'X' WHERE VBELN = IM_VBELN.
      ENDIF.

    ENDIF.
  ENDIF.
  REFRESH IT_DATA .
ENDFUNCTION.