FUNCTION ZWM_CRATE_IDENTIFIER_RFC.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IM_USER) TYPE  WWWOBJID OPTIONAL
*"     VALUE(IM_PLANT) TYPE  WERKS_D OPTIONAL
*"     VALUE(IM_CRATE) TYPE  ZZCRATE OPTIONAL
*"  EXPORTING
*"     VALUE(EX_RETURN) TYPE  BAPIRET2
*"     VALUE(EX_BIN) TYPE  LGPLA
*"     VALUE(EX_AVAIL_QTY) TYPE  LQUA_VERME
*"     VALUE(EX_ST_BIN_TYPE) TYPE  LVS_LPTYP
*"----------------------------------------------------------------------

* Clear exports
  CLEAR: EX_RETURN, EX_BIN, EX_AVAIL_QTY, EX_ST_BIN_TYPE.

* ── Input validation ──
  IF IM_USER IS INITIAL.
    EX_RETURN = VALUE #( TYPE = 'E' MESSAGE = 'USER ID SHOULD NOT BE BLANK' ).
    RETURN.
  ENDIF.

  IF IM_PLANT IS INITIAL.
    EX_RETURN = VALUE #( TYPE = 'E' MESSAGE = 'PLANT SHOULD NOT BE BLANK' ).
    RETURN.
  ENDIF.

  IF IM_CRATE IS INITIAL.
    EX_RETURN = VALUE #( TYPE = 'E' MESSAGE = 'CRATE SHOULD NOT BE BLANK' ).
    RETURN.
  ENDIF.

* ── User-plant validation ──
  IM_USER = |{ IM_USER ALPHA = IN }|.

  SELECT SINGLE WERKS FROM ZWM_USR02
    INTO @DATA(LV_PLANT)
    WHERE BNAME = @IM_USER
      AND WERKS = @IM_PLANT.
  IF SY-SUBRC NE 0.
    EX_RETURN = VALUE #( TYPE = 'E' MESSAGE = 'PLANT AND USER DOESN''T MATCH' ).
    RETURN.
  ENDIF.

* ── Get storage type from DC master ──
  SELECT SINGLE LGTYP, LGNUM FROM ZWM_DC_MASTER
    INTO ( @DATA(LV_LGTYP), @DATA(LV_LGNUM) )
    WHERE WERKS = @IM_PLANT.
  IF SY-SUBRC NE 0.
    EX_RETURN = VALUE #( TYPE = 'E' MESSAGE = 'PLANT NOT FOUND IN DC MASTER' ).
    RETURN.
  ENDIF.

* ── Get bin details for crate with stock aggregation ──
  SELECT _LAGP~LGPLA, _LAGP~LPTYP,
         SUM( _LQUA~VERME ) AS AVAIL_QTY
    FROM ZWM_CRATE AS _CRATE
    INNER JOIN LAGP AS _LAGP
      ON  _LAGP~LGPLA = _CRATE~LGPLA
      AND _LAGP~LGTYP = _CRATE~LGTYP
      AND _LAGP~LGNUM = _CRATE~LGNUM
    LEFT JOIN LQUA AS _LQUA
      ON  _LQUA~LGPLA = _LAGP~LGPLA
      AND _LQUA~LGTYP = _LAGP~LGTYP
      AND _LQUA~LGNUM = _LAGP~LGNUM
      AND _LQUA~WERKS = @IM_PLANT
    WHERE _CRATE~CRATE = @IM_CRATE
      AND _LAGP~LGTYP  = @LV_LGTYP
      AND _LAGP~LGNUM  = @LV_LGNUM
    GROUP BY _LAGP~LGPLA, _LAGP~LPTYP
    INTO @DATA(LS_BIN)
    UP TO 1 ROWS.
  ENDSELECT.

  IF SY-SUBRC NE 0.
    EX_RETURN = VALUE #( TYPE = 'E' MESSAGE = 'CRATE DOESN''T MATCH' ).
    RETURN.
  ENDIF.

* ── Set export values ──
  EX_BIN         = LS_BIN-LGPLA.
  EX_AVAIL_QTY   = LS_BIN-AVAIL_QTY.
  EX_ST_BIN_TYPE = LS_BIN-LPTYP.

  IF LS_BIN-AVAIL_QTY GT 0.
    EX_RETURN = VALUE #( TYPE = 'S' MESSAGE = 'BIN AND CRATE MAPPED WITH AVAILABLE STOCK' ).
  ELSE.
    EX_RETURN = VALUE #( TYPE = 'S' MESSAGE = 'BIN AND CRATE MAPPED WITH NO STOCK' ).
  ENDIF.

ENDFUNCTION.