FUNCTION ZSDC_ART_STA_RFC.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(EX_DATA) TYPE  ZSDC_ART_STATUS_TT OPTIONAL
*"  EXPORTING
*"     VALUE(EX_RETURN) TYPE  BAPIRET2
*"----------------------------------------------------------------------
* ══ Optimized by ABAP AI Studio — 04-Apr-2026 ══
* BEFORE: 3x SELECT SINGLE inside LOOP (N database calls per validation)
* AFTER:  3 bulk SELECTs before loop + READ TABLE BINARY SEARCH
* Expected: 5-10x faster for large datasets

  DATA: IT_DATA1 TYPE TABLE OF ZSDC_ART_STATUS_ST.
  DATA: IT_DATA2 TYPE TABLE OF ZSDC_ART_STATUS.
  DATA: LT_RETURN TYPE TABLE OF BAPIRET2.

  DATA(IT_DATA) = EX_DATA[].

  SORT IT_DATA BY ARTICLE_NO STORE_CODE.
  DELETE ADJACENT DUPLICATES FROM IT_DATA COMPARING ARTICLE_NO STORE_CODE.

  CHECK IT_DATA IS NOT INITIAL.

  " ── Bulk load validation tables BEFORE the loop ──────────────
  " 1. Existing records in ZSDC_ART_STATUS
  SELECT ARTICLE_NO, STORE_CODE FROM ZSDC_ART_STATUS
    INTO TABLE @DATA(LT_EXISTING)
    FOR ALL ENTRIES IN @IT_DATA
    WHERE ARTICLE_NO = @IT_DATA-ARTICLE_NO
      AND STORE_CODE = @IT_DATA-STORE_CODE.
  SORT LT_EXISTING BY ARTICLE_NO STORE_CODE.

  " 2. Valid materials from MARA
  SELECT MATNR FROM MARA
    INTO TABLE @DATA(LT_VALID_MATNR)
    FOR ALL ENTRIES IN @IT_DATA
    WHERE MATNR = @IT_DATA-ARTICLE_NO.
  SORT LT_VALID_MATNR BY MATNR.

  " 3. Valid plants from T001W
  SELECT WERKS FROM T001W
    INTO TABLE @DATA(LT_VALID_PLANT)
    FOR ALL ENTRIES IN @IT_DATA
    WHERE WERKS = @IT_DATA-STORE_CODE
      AND VLFKZ = 'A'.
  SORT LT_VALID_PLANT BY WERKS.

  " ── Validate using READ TABLE (no DB calls in loop) ──────────
  LOOP AT IT_DATA ASSIGNING FIELD-SYMBOL(<FS_VALIDATE>).
    " Check duplicate
    READ TABLE LT_EXISTING TRANSPORTING NO FIELDS
      WITH KEY ARTICLE_NO = <FS_VALIDATE>-ARTICLE_NO
               STORE_CODE = <FS_VALIDATE>-STORE_CODE
      BINARY SEARCH.
    IF SY-SUBRC IS INITIAL.
      EX_RETURN = VALUE #( TYPE = 'E'
        MESSAGE = |{ TEXT-002 }-{ <FS_VALIDATE>-ARTICLE_NO }-{ TEXT-003 } { <FS_VALIDATE>-STORE_CODE }-{ TEXT-004 }| ).
      RETURN.
    ENDIF.

    " Validate material
    READ TABLE LT_VALID_MATNR TRANSPORTING NO FIELDS
      WITH KEY MATNR = <FS_VALIDATE>-ARTICLE_NO
      BINARY SEARCH.
    IF SY-SUBRC NE 0.
      EX_RETURN = VALUE #( TYPE = 'E'
        MESSAGE = |{ TEXT-005 }-{ <FS_VALIDATE>-ARTICLE_NO }| ).
      RETURN.
    ENDIF.

    " Validate plant
    READ TABLE LT_VALID_PLANT TRANSPORTING NO FIELDS
      WITH KEY WERKS = <FS_VALIDATE>-STORE_CODE
      BINARY SEARCH.
    IF SY-SUBRC NE 0.
      EX_RETURN = VALUE #( TYPE = 'E'
        MESSAGE = |{ TEXT-006 }-{ <FS_VALIDATE>-STORE_CODE }| ).
      RETURN.
    ENDIF.
  ENDLOOP.

  IT_DATA2 = VALUE #( FOR LS_DATA IN IT_DATA
                    ( STORE_CODE = LS_DATA-STORE_CODE
                      ARTICLE_NO = LS_DATA-ARTICLE_NO
                      ART_TYPE   = LS_DATA-ART_TYPE
                      CREATED_DATE = SY-DATUM
                      CREATED_TIME = SY-UZEIT
                      CREATED_BY   = SY-UNAME ) ).

  MODIFY ZSDC_ART_STATUS FROM TABLE IT_DATA2.
  COMMIT WORK.

  EX_RETURN = VALUE #( TYPE = 'S' MESSAGE = TEXT-007 ).

ENDFUNCTION.
