// Deploy timestamp: 2026-03-26T09:47:48.990Z
using SAP.Middleware.Connector;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;
using Vendor_Application_MVC.Controllers;

namespace Vendor_SRM_Routing_Application.Controllers.Finance
{
    public class ZFI_PI_DATA_RFCController : BaseController
        {
                [HttpPost]
                        [Route("api/ZFI_PI_DATA_RFC")]
                                public async Task<IHttpActionResult> ProcessFinancePostingInvoices([FromBody] ZFI_PI_DATA_RFC_Request request)
                                        {
                                                    return await Task.Run<IHttpActionResult>(() =>
                                                                {
                                                                                try
                                                                                                {
                                                                                                                    var dest = RfcDestinationManager.GetDestination(SapConfig);
                                                                                                                                        var repo = dest.Repository;
                                                                                                                                                            var func = repo.CreateFunction("ZFI_PI_DATA_RFC");
                                                                                                                                                            
                                                                                                                                                                                func.SetValue("IT_POSTING_LOW", request.IT_POSTING_LOW ?? "");
                                                                                                                                                                                                    func.SetValue("IT_POSTING_HIGH", request.IT_POSTING_HIGH ?? "");
                                                                                                                                                                                                    
                                                                                                                                                                                                                        func.Invoke(dest);
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                            var ret = func.GetStructure("EX_RETURN");
                                                                                                                                                                                                                                                                string msgType = ret.GetString("TYPE");
                                                                                                                                                                                                                                                                                    string msgText = ret.GetString("MESSAGE");
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                        if (msgType == "E" || msgType == "A")
                                                                                                                                                                                                                                                                                                                                return BadRequest(msgText);
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                    var table = func.GetTable("IT_FINAL");
                                                                                                                                                                                                                                                                                                                                                                        var rows = new List<Dictionary<string, string>>();
                                                                                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < table.Count; i++)
                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                        table.CurrentIndex = i;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                rows.Add(new Dictionary<string, string>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { "INV_DOC_NO",      table.GetString("INV_DOC_NO") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { "FISCAL_YEAR",     table.GetString("FISCAL_YEAR") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { "DOCUMENT_DATE",   table.GetString("DOCUMENT_DATE") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { "POSTING_DATE",    table.GetString("POSTING_DATE") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { "REFERENCE",       table.GetString("REFERENCE") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { "INVOICING_PARTY", table.GetString("INVOICING_PARTY") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { "GROSS_INV_AMNT",  table.GetString("GROSS_INV_AMNT") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { "VALUE_ADDED_TAX", table.GetString("VALUE_ADDED_TAX") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { "TAX_CODE",        table.GetString("TAX_CODE") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { "PURCHASING_DOC",  table.GetString("PURCHASING_DOC") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { "REFERENCE_DOC",   table.GetString("REFERENCE_DOC") }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return Ok(new { Status = true, Message = msgText, Data = rows });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            catch (Exception ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return InternalServerError(ex);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        public class ZFI_PI_DATA_RFC_Request
        {
                    public string IT_POSTING_LOW  { get; set; }
                    public string IT_POSTING_HIGH { get; set; }
        }
}
