FUNCTION ZWM_STORE_GET_PICKLIST_PPL.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IM_WERKS) TYPE  WERKS_D
*"     VALUE(IM_PICNR) TYPE  ZPICNR
*"     VALUE(IM_LGORT) TYPE  LGORT_D DEFAULT '0002'
*"     VALUE(IM_LGNUM) TYPE  LGNUM DEFAULT 'SDC'
*"  EXPORTING
*"     VALUE(EX_RETURN) TYPE  BAPIRET2
*"  TABLES
*"      ET_EAN_DATA STRUCTURE  MARM OPTIONAL
*"      ET_PICKLIST TYPE  ZWM_STORE_STRU_T OPTIONAL
*"--------------------------------------------------------------------

  DATA: LT_LQUA    TYPE STANDARD TABLE OF LQUA,
        LT_ST_PICK TYPE STANDARD TABLE OF ZST_PICK.

  DATA: LS_PICK     TYPE ZST_PICK,
        LS_PICKLIST TYPE ZWM_STORE_STRU,
        LS_LQUA     TYPE LQUA.

  DATA: L_PICNR  TYPE ZPICNR,
        LV_REQ_Q TYPE MENGE_D.

  FIELD-SYMBOLS: <LFS_PICK> TYPE ZST_PICK.

  TYPES: BEGIN OF TY_MARA,
           MATNR TYPE MATNR,
           MATKL TYPE MATKL,
         END OF TY_MARA.

  TYPES: BEGIN OF TY_T023T,
           MATKL TYPE MATKL,
           WGBEZ TYPE WGBEZ,
         END OF TY_T023T.

  DATA: LT_MARA  TYPE TABLE OF TY_MARA,
        LT_T023T TYPE TABLE OF TY_T023T,
        LS_MARA  TYPE TY_MARA,
        LS_T023T TYPE TY_T023T.

  SELECT SINGLE * FROM ZWM_ST_ACTIVE
          INTO @DATA(GS_ST_ACTIVE)
          WHERE LGNUM = 'SDC'
            AND WERKS = @IM_WERKS.

  IF SY-SUBRC IS INITIAL.
    IF GS_ST_ACTIVE-PICK11 IS INITIAL .
      EX_RETURN-MESSAGE  = 'Picklist not allowed'.
      EX_RETURN-TYPE = 'E'.
      EXIT.
    ENDIF.
  ELSE.
    EX_RETURN-MESSAGE  = 'Entry not maintained in zsdc_st_allow'.
    EX_RETURN-TYPE = 'E'.
    EXIT.
  ENDIF.

  IF IM_PICNR IS INITIAL .
    EX_RETURN-MESSAGE  = 'Blank Picklist not allowed'.
    EX_RETURN-TYPE = 'E'.
    EXIT.
  ENDIF.

  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT  = IM_PICNR
    IMPORTING
      OUTPUT = L_PICNR.

  SELECT * FROM ZST_PICK
          INTO  TABLE LT_ST_PICK
           WHERE PICNR EQ L_PICNR
       AND LGNUM EQ IM_LGNUM
       AND WERKS EQ IM_WERKS
       AND LGORT EQ IM_LGORT
       AND LGTYP EQ IM_WERKS+1(3).
  IF SY-SUBRC IS  NOT INITIAL.
    EX_RETURN-TYPE = C_ERROR.
    EX_RETURN-MESSAGE = 'Invalid Picklist'.
    RETURN .
  ELSE.
    LOOP AT LT_ST_PICK ASSIGNING <LFS_PICK>.
      IF <LFS_PICK>-PICK_QTY LE <LFS_PICK>-PICKED_QTY .
        <LFS_PICK>-WERKS = ''.
      ENDIF.
    ENDLOOP.
    DELETE LT_ST_PICK WHERE WERKS IS INITIAL.

    IF LT_ST_PICK[] IS INITIAL.
      EX_RETURN-TYPE = C_ERROR.
      EX_RETURN-MESSAGE = 'Picklist Closed'.
      RETURN .
    ENDIF.

*Check avaialable stock
    SELECT lgnum matnr werks lgtyp lgpla lgort verme meins
      FROM LQUA
            INTO TABLE LT_LQUA
            FOR ALL ENTRIES IN LT_ST_PICK
            WHERE  LGNUM EQ IM_LGNUM
       AND WERKS EQ IM_WERKS
       AND LGORT EQ IM_LGORT
       AND LGTYP EQ IM_WERKS+1(3)
       AND LGPLA = LT_ST_PICK-LGPLA.

    SORT LT_LQUA BY MATNR LGPLA.
    LOOP AT LT_ST_PICK ASSIGNING <LFS_PICK>.
      <LFS_PICK>-VERME = ''.

      READ TABLE LT_LQUA INTO LS_LQUA WITH KEY MATNR = <LFS_PICK>-MATNR
                                               LGPLA = <LFS_PICK>-LGPLA
                                               BINARY SEARCH .
      IF SY-SUBRC IS INITIAL .
        LV_REQ_Q =  <LFS_PICK>-PICK_QTY -  <LFS_PICK>-PICKED_QTY .

        IF LV_REQ_Q LE LS_LQUA-VERME .
          <LFS_PICK>-VERME = LV_REQ_Q.
        ELSE.
          <LFS_PICK>-VERME = LS_LQUA-VERME.
        ENDIF.
      ELSE.
        <LFS_PICK>-WERKS = ''.
      ENDIF.
    ENDLOOP.
    DELETE LT_ST_PICK WHERE WERKS IS INITIAL.
    DELETE LT_ST_PICK WHERE VERME LT 0.
  ENDIF.

  IF LT_ST_PICK IS NOT INITIAL.
    SELECT MATNR MATKL
     FROM MARA
     INTO TABLE LT_MARA
     FOR ALL ENTRIES IN LT_ST_PICK
     WHERE MATNR = LT_ST_PICK-MATNR.
    IF SY-SUBRC = 0.
      SELECT MATKL WGBEZ
        FROM T023T
        INTO TABLE LT_T023T
        FOR ALL ENTRIES IN LT_MARA
        WHERE MATKL = LT_MARA-MATKL.
    ENDIF.
  ENDIF.

  LOOP AT  LT_ST_PICK ASSIGNING <LFS_PICK>.
    LS_PICKLIST-PICNR = <LFS_PICK>-PICNR.
    LS_PICKLIST-PLANT = <LFS_PICK>-WERKS.
    LS_PICKLIST-MATERIAL = <LFS_PICK>-MATNR.
    LS_PICKLIST-BIN = <LFS_PICK>-LGPLA.
    LS_PICKLIST-STOR_LOC = <LFS_PICK>-LGORT.
    LS_PICKLIST-STORAGE_TYPE = <LFS_PICK>-LGTYP.
    LS_PICKLIST-AVL_STOCK = <LFS_PICK>-VERME.
    LS_PICKLIST-PICK_QTY = <LFS_PICK>-VERME.
    READ TABLE LT_MARA INTO LS_MARA WITH KEY MATNR = <LFS_PICK>-MATNR.
    IF SY-SUBRC = 0.
      READ TABLE LT_T023T INTO LS_T023T WITH KEY MATKL = LS_MARA-MATKL.
      IF SY-SUBRC = 0.
        LS_PICKLIST-MATKL = LS_T023T-MATKL.
        LS_PICKLIST-WGBEZ = LS_T023T-WGBEZ.
      ENDIF.
    ENDIF.

    APPEND LS_PICKLIST TO ET_PICKLIST .
    CLEAR LS_PICKLIST .
  ENDLOOP.

  IF ET_PICKLIST[]  IS NOT INITIAL.
    CALL FUNCTION 'ZWM_STORE_GET_EAN_DATA'
      EXPORTING
        IT_DATA     = ET_PICKLIST[]
      TABLES
        ET_EAN_DATA = ET_EAN_DATA.
  ELSE.
    EX_RETURN-TYPE = C_ERROR.
    EX_RETURN-MESSAGE = 'No Stock Data found'.
  ENDIF.

ENDFUNCTION.