FUNCTION ZWM_STORE_BIN_CON_PICKING_HU.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IM_WERKS) TYPE  WERKS_D
*"     VALUE(IM_LGNUM) TYPE  LGNUM DEFAULT 'SDC'
*"     VALUE(IM_USER) TYPE  WWWOBJID OPTIONAL
*"     VALUE(IM_EXIDV) TYPE  EXIDV OPTIONAL
*"     VALUE(IM_PICNR) TYPE  ZPICNR OPTIONAL
*"  EXPORTING
*"     VALUE(EX_RETURN) TYPE  BAPIRET2
*"     VALUE(EX_TANUM) TYPE  TANUM
*"  TABLES
*"      IT_DATA TYPE  ZWM_STORE_STRU_T OPTIONAL
*"----------------------------------------------------------------------
  BREAK-POINT ID Z_V2CHECK.
  DATA: LR_DATA    TYPE REF TO ZWM_STORE_STRU.


  DATA: L_EXIDV    TYPE EXIDV,
        L_NUMBER   TYPE TANUM,
        L_DOC_TYPE TYPE CHAR1.

  DATA: LT_LTAP_CREATE TYPE STANDARD TABLE OF LTAP_CREAT   INITIAL SIZE 0,
        LT_LTAP        TYPE STANDARD TABLE OF LTAP_VB      INITIAL SIZE 0,
        LT_LQUA        TYPE STANDARD TABLE OF LQUA         INITIAL SIZE 0,
        LT_PICK        TYPE STANDARD TABLE OF ZST_BIN_CONS INITIAL SIZE 0,
        LT_DATA        TYPE   ZWM_STORE_STRU_T.

  DATA: LS_LTAP_CREATE TYPE LTAP_CREAT,
        LS_PICK        TYPE ZST_BIN_CONS,
        LS_DATA        TYPE ZWM_STORE_STRU,
        L_TANUM        TYPE TANUM,
        LV_PICNR       TYPE ZPICNR,
        L_USER         TYPE WWWOBJID.

  FIELD-SYMBOLS: <LFS_PICK> TYPE ZST_BIN_CONS,
                 <LFS_DATA> TYPE ZWM_STORE_STRU.
  BREAK-POINT ID Z_V2CHECK.
  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT  = IM_USER
    IMPORTING
      OUTPUT = L_USER.

  TRANSLATE L_USER TO UPPER CASE.

  IF IT_DATA[] IS INITIAL.
    EX_RETURN-TYPE = C_ERROR.
    EX_RETURN-MESSAGE = 'No Data For Process'.
    RETURN.
  ENDIF.

  IF IM_EXIDV IS NOT INITIAL.
    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
      EXPORTING
        INPUT  = IM_EXIDV
      IMPORTING
        OUTPUT = L_EXIDV.
  ENDIF.
 DATA: LV_MATNR TYPE MATNR18.
  LOOP AT IT_DATA REFERENCE INTO LR_DATA.
    TRANSLATE LR_DATA->BIN TO UPPER CASE .

*Convert into internal format
*    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
*      EXPORTING
*        input  = lr_data->material
*      IMPORTING
*        output = .

          LV_MATNR = |{ LR_DATA->MATERIAL ALPHA = OUT } |.
        LV_MATNR = |{ LV_MATNR ALPHA = IN } |.
        LR_DATA->MATERIAL = LV_MATNR.

  ENDLOOP.

  LT_DATA[] = IT_DATA[].
  SORT LT_DATA BY BIN .
  DELETE ADJACENT DUPLICATES FROM LT_DATA COMPARING BIN.

  SELECT *
    FROM LQUA
    INTO TABLE LT_LQUA
    FOR ALL ENTRIES IN LT_DATA
    WHERE LGNUM = 'SDC'
      AND WERKS = IM_WERKS
      AND LGTYP = IM_WERKS+1(3)
      AND LGPLA = LT_DATA-BIN
      AND LGORT = '0002'.

  IF LT_LQUA[] IS NOT INITIAL.
    PERFORM F_MOVE_DATA_TO_V11_BIN_CON USING LT_LQUA .
  ENDIF.

  IF L_EXIDV IS INITIAL.
    LT_DATA[] = IT_DATA[].
    PERFORM F_BIN_CONSOLIDATION_CREATE_HU USING LT_DATA IM_WERKS L_EXIDV EX_RETURN.
  ENDIF.

  IF EX_RETURN-TYPE NE 'E'.
    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
      EXPORTING
        INPUT  = IM_PICNR
      IMPORTING
        OUTPUT = LV_PICNR.

    SELECT *
      FROM ZST_BIN_CONS
      INTO TABLE LT_PICK
      WHERE PICNR = LV_PICNR
        AND EXIDV = ''
        AND ELIKZ = ''.

    SORT LT_PICK BY LGPLA MATNR.

    LOOP AT IT_DATA ASSIGNING <LFS_DATA>.
      READ TABLE LT_PICK ASSIGNING <LFS_PICK> WITH KEY LGPLA = <LFS_DATA>-BIN
                                                       MATNR = <LFS_DATA>-MATERIAL
                                                       BINARY SEARCH.
      IF SY-SUBRC IS INITIAL.
        <LFS_PICK>-SCAN = <LFS_DATA>-SCAN_QTY.
        <LFS_PICK>-EXIDV = L_EXIDV.
      ELSE.
        LS_PICK-PICNR = LV_PICNR.
        LS_PICK-LGNUM = 'SDC'.
        LS_PICK-WERKS = IM_WERKS.
        LS_PICK-LGPLA = <LFS_DATA>-BIN.
        LS_PICK-LGORT = '0002'.


        LV_MATNR = |{ <LFS_DATA>-MATERIAL ALPHA = OUT } |.
        LV_MATNR = |{ LV_MATNR ALPHA = IN } |.
        <LFS_DATA>-MATERIAL = LV_MATNR.
        LS_PICK-MATNR = LV_MATNR.




        SELECT SINGLE MATKL FROM MARA INTO LS_PICK-MATKL  WHERE MATNR = <LFS_DATA>-MATERIAL.
        SELECT SINGLE MAKTX FROM MAKT INTO LS_PICK-MAKTX WHERE MATNR = <LFS_DATA>-MATERIAL AND SPRAS = SY-LANGU.
        SELECT SINGLE WGBEZ FROM T023T INTO  LS_PICK-WGBEZ WHERE MATKL = LS_PICK-MATKL AND SPRAS = SY-LANGU.

        LS_PICK-SCAN = <LFS_DATA>-SCAN_QTY.
        LS_PICK-LGTYP = IM_WERKS+1(3).
        LS_PICK-MEINS = 'EA'.
        LS_PICK-EXIDV = L_EXIDV.
        LS_PICK-ERDAT = SY-DATUM.
        LS_PICK-ERNAM = SY-UNAME.
        LS_PICK-ERZET = SY-UZEIT.
        LS_PICK-AEDAT = SY-DATUM.
        LS_PICK-AENAM = SY-UNAME.
        LS_PICK-AEZET = SY-UZEIT.
        APPEND LS_PICK TO LT_PICK.
        CLEAR LS_PICK.
      ENDIF.
    ENDLOOP.

    MODIFY ZST_BIN_CONS FROM TABLE LT_PICK.
    COMMIT WORK AND WAIT.
    EX_RETURN-TYPE = 'S'.
    CONCATENATE L_EXIDV  'Saved' INTO  EX_RETURN-MESSAGE .
  ENDIF.
ENDFUNCTION.