using SAP.Middleware.Connector;
using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using Vendor_Application_MVC.Controllers;

namespace Vendor_SRM_Routing_Application.Controllers.Vendor_SRM_Routing
{
    public class ZVEND_CODE_AUTH_RFCController : BaseController
        {
                [HttpPost]
                        [Route("api/ZVEND_CODE_AUTH_RFC")]
                                public async Task<HttpResponseMessage> ZVEND_CODE_AUTH_RFC([FromBody] ZVEND_CODE_AUTH_RFCRequest request)
                                        {
                                                    return await Task.Run(() =>
                                                                {
                                                                                try
                                                                                                {
                                                                                                                    if (request == null)
                                                                                                                                            return Request.CreateResponse(HttpStatusCode.OK, new { Status = "E", Message = "Request cannot be null" });
                                                                                                                                            
                                                                                                                                                                if (string.IsNullOrEmpty(request.IM_VEND_ID))
                                                                                                                                                                                        return Request.CreateResponse(HttpStatusCode.OK, new { Status = "E", Message = "IM_VEND_ID is required" });
                                                                                                                                                                                        
                                                                                                                                                                                                            if (string.IsNullOrEmpty(request.IM_PASSWORD))
                                                                                                                                                                                                                                    return Request.CreateResponse(HttpStatusCode.OK, new { Status = "E", Message = "IM_PASSWORD is required" });
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                        RfcConfigParameters rfcPar = BaseController.rfcConfigparametersproduction();
                                                                                                                                                                                                                                                                            RfcDestination dest = RfcDestinationManager.GetDestination(rfcPar);
                                                                                                                                                                                                                                                                                                RfcRepository rfcrep = dest.Repository;
                                                                                                                                                                                                                                                                                                                    IRfcFunction myfun = rfcrep.CreateFunction("ZVEND_CODE_AUTH_RFC");
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        myfun.SetValue("IM_VEND_ID", request.IM_VEND_ID);
                                                                                                                                                                                                                                                                                                                                                            myfun.SetValue("IM_PASSWORD", request.IM_PASSWORD);
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                myfun.Invoke(dest);
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    IRfcStructure EX_RETURN = myfun.GetStructure("EX_RETURN");
                                                                                                                                                                                                                                                                                                                                                                                                                        string returnType = EX_RETURN.GetString("TYPE");
                                                                                                                                                                                                                                                                                                                                                                                                                                            string returnMessage = EX_RETURN.GetString("MESSAGE");
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (returnType == "E")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return Request.CreateResponse(HttpStatusCode.OK, new { Status = "E", Message = returnMessage });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return Request.CreateResponse(HttpStatusCode.OK, new { Status = "S", Message = returnMessage });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            catch (Exception ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Request.CreateResponse(HttpStatusCode.OK, new { Status = "E", Message = ex.Message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        public class ZVEND_CODE_AUTH_RFCRequest
        {
                    public string IM_VEND_ID { get; set; }
                    public string IM_PASSWORD { get; set; }
        }
}
